version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:9090"
    environment:
      - PORT=9090
      - MONGODB_URI=mongodb+srv://flashcard:MSOc13Sjc8c0vshn@cluster.j9kfm6e.mongodb.net/?retryWrites=true&w=majority&appName=Cluster/flashcard_db
      - JWT_SECRET=your-secret-key-here
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - LINKEDIN_CLIENT_ID=your-linkedin-client-id
      - LINKEDIN_CLIENT_SECRET=your-linkedin-client-secret
      - STRIPE_SECRET_KEY=your-stripe-secret-key
      - AWS_ACCESS_KEY_ID=your-aws-access-key
      - AWS_SECRET_ACCESS_KEY=your-aws-secret-key
      - AWS_REGION=us-east-1
      - AWS_S3_BUCKET=your-s3-bucket
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - flashcard-network

  mongo:
    image: mongo:6.0
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=flashcard_db
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - flashcard-network

volumes:
  mongo_data:

networks:
  flashcard-network:
    driver: bridge 